### ISSUE TITLE
TO-DO

### ISSUE THREAD

**Issue by azhe825** [ai-se/ML-assisted-SLR#20]
- [x] Three-section white paper
  - [x] abstract and introduction
  - [x] background
    - [x] SLR
    - [x] Primary study selection (need one more graph)
    - [x] related work in SE community
    - [x] related work in Biomedical Engineering community
    - [x] related work in Litigation community
  - [x] method
- [x] Case Studies
  - [x] one on SLR data
  - [x] [Hall, Tracy, Sarah Beecham, David Bowes, David Gray, and Steve Counsell. "A Systematic Literature Review on Fault Prediction Performance in Software Engineering."](https://www.researchgate.net/profile/Sarah_Beecham/publication/224260840_A_Systematic_Review_of_Fault_Prediction_Performance_in_Software_Engineering/links/00b7d517ffd6eae67f000000.pdf)
  - [x] Experiment on different margins
  - [x] Boolean comparisons
- [x] Whole paper draft
  - [x] experiments
  - [x] research questions
  - [x] threats to validity
  - [x] conclusion and future work
  - [x] rewrite abstract and introduction
- [ ] Refactory
  - [ ] make figures clear (fonts, colors, rule out white spaces)
  - [ ] merge RQ1 with background
